### ISSUE TITLE
Breadcrumbs are in a specific order so using an "ordered" list seems appropriate

### ISSUE THREAD

**Issue by acrogenesis** [zachinglis/crummy#57]
I think crummy should be using `<ol>` instead of `<ul>`.  Breadcrumbs are in a very specific order and so using an "ordered" list seems appropriate.

I can make the PR if you wish.

**Comment by zachinglis** [comment]
Very logical opinion. I agree with you. Please do :)

**Comment by n-rodriguez** [comment]
Hi there! Can you please cut a new release with this patch?

Thx!

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by acrogenesis** [comment]
@n-rodriguez you can always do `gem "crummy", github: "zachinglis/crummy", branch: "master"

**Comment by n-rodriguez** [comment]
That's what I do and I want to avoid that.

**Comment by n-rodriguez** [comment]
@zachinglis this issue can be closed. thank you!

**Comment by n-rodriguez** [comment]
ping @zachinglis

**Comment by acrogenesis** [comment]
:)
